### ISSUE TITLE
Fix Django 1.9 warning

### ISSUE THREAD

**Issue by jonashaag** [dyve/django-bootstrap3#290] opened 2015-12-09 10:08 UTC
```
django-bootstrap3/bootstrap3/utils.py:142: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return template.render(Context(context))
```

**Comment by troygrosfield** [comment] 2016-01-22 19:18
:+1:

**Comment by ncolton** [comment] 2016-01-22 22:37
This looks like a duplicate of #279.

**Comment by dyve** [comment] 2016-02-12 11:02
Fix is in place now in develop branch, but I think it's ugly. Improvements welcome, as long as tests pass (keep Travis and tox happy).

**Closed by dyve** 2016-02-12 11:02 UTC

**Comment by jonashaag** [comment] 2016-02-12 11:49
```py
    # For Django < 1.8, render with a Context object
    if VERSION < (1,8):
        return render(Context(context))
    else:
        return render(context)
```

This should be the correct way. If this gets you tracebacks, could you paste them here?

**Comment by dyve** [comment] 2016-02-12 12:04
@jonashaag That code fails if context already *is* a Context().

**Comment by dyve** [comment] 2016-02-12 12:05
And that code makes the tests fail by complaining that a dict object provider to render function.

See https://github.com/dyve/django-bootstrap3/pull/297

**Comment by jonashaag** [comment] 2016-02-12 14:02
> @jonashaag That code fails if context already is a Context().

Well that's illegal with the new Django API so the code that passes Context objects needs updating

**Comment by dyve** [comment] 2016-02-12 14:14
Agreed

**Comment by dyve** [comment] 2016-02-12 14:27
I pushed a non-passing version (work in progress) to develop. The key may be to make some tests more explicit. Feel free to point out errors and such (I know they are in there).

**Comment by jonashaag** [comment] 2016-02-12 17:01
The problem is that you're using `from django.template import Template` in the tests while you should be using `from django.template.backends.django import Template`

**Comment by dyve** [comment] 2016-02-12 17:02
I just found that out, fixing code now :-)

**Comment by dyve** [comment] 2016-02-12 17:17
It wasn't even that in the django-bootstrap3 code.

The culprit was a custom template tag with takes_context=True. Even in Django 1.9, that still results in context variable with a Context object, not a dict. Once you flatten the Context into a dict, all warnings are gone.

**Comment by dyve** [comment] 2016-02-12 17:22
Fix in develop branch
