### ISSUE TITLE
Demo app error: cannot find admin template widgets

### ISSUE THREAD

**Issue by zorun** [dyve/django-bootstrap3#403] opened 2017-05-23 17:30 UTC
When running the demo app and accessing e.g. http://localhost:8000/form there is an error:

```
TemplateDoesNotExist at /form
admin/widgets/split_datetime.html
```

Adding `django.contrib.admin` to the `INSTALLED_APPS` of the demo project solved the issue.  This is using Django 1.11.1 with Python 2.7.

**Comment by arbego** [comment] 2017-05-26 18:33
Hello, it says "No module named admindjango.contrib" when I add "django.contrib.admin" to the "INSTALLED_APPS". Any ideas?

**Comment by dyve** [comment] 2017-05-27 06:38
Bug confirmed, will fix it in next release. Already fixed in the Bootstrap 4 version.

**Comment by dyve** [comment] 2017-08-18 07:03
Has since been fixed, thanks for reporting.

**Closed by dyve** 2017-08-18 07:03 UTC
