### ISSUE TITLE
Pre-filled form results in errors even when valid

### ISSUE THREAD

**Issue by ned2** [dyve/django-bootstrap3#338] opened 2016-09-05 14:58 UTC
When I render a form that has some fields already filled in, bootstrap renders these fields and at least one more as containing errors. However the form is valid, as I can submit it successfully as is. The form I'm adding to the context looks something like this, where both fields are foreign keys:

    form = SomeForm({'user': user, 'query': query})

The foreign keys get 'Select a valid choice. That choice is not one of the available choices.' whereas another CharField with choices gets 'This field is required.' But as mentioned these all have valid values.

I'm on Django 1.10.

**Comment by dyve** [comment] 2016-09-05 15:50
The problem is new form handling in 1.10 probably. 
Can you see if 1.9 works?
If you could submit a (failing) test that would be awesome.

**Comment by ned2** [comment] 2016-09-06 04:11
Seems to also be a problem in 1.9 and 1.8. Will try and submit a test when I get a chance.

**Comment by dyve** [comment] 2016-09-06 07:12
Thanks Ned, much appreciated.

**Comment by ned2** [comment] 2016-09-06 08:59
Hmmm, I'm struggling to run the tests... Running `python setup.py test` in a fresh clone of the repo complains that DJANGO_SETTINGS_MODULE is not set. I do `export DJANGO_SETTINGS_MODULE=testsettings` and that error is replaced by 'django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.' I tried on both Django 1.10 and 1.9.

Should I be doing anything else?

**Comment by dyve** [comment] 2016-09-14 06:52
Run the tests using `tox` or `./manage.py test`. I'll make sure `setup.py test` does something more useful.

**Comment by ned2** [comment] 2016-09-15 05:22
So I've worked out that the problem was that I should have been passing the initial dictionary of data in with the `initial` keyword meant for exactly this purpose. ie 

    form = SomeForm(initial={'user': user, 'query': query})

Then django-bootstrap3 behaves exactly as expected. Without using the `initial` keyword, the form that is sent through becomes a bound form, so I guess this is what triggers the error, as it looks like a form that has been submitted by the user but is incomplete.

Do you think this still warrants a test case? It's not clear to me what the expected behaviour should be here.

**Comment by dyve** [comment] 2016-09-15 05:24
Good find Ned. I think we can close this, expected behaviour looks OK to me.

**Closed by dyve** 2016-09-15 05:24 UTC
Labels: awaiting feedback
