### ISSUE TITLE
FileField and ImageField are rendered without class

### ISSUE THREAD

**Issue by beruic** [dyve/django-bootstrap3#282] opened 2015-10-14 13:18 UTC
Shouldn't `FileField` and `ImageField` be rendered with `class="form-control"`? I get them rendered without class at all. This is what I typically get for a field of one of these types (prettified):

```html
<div class="form-group">
    <label class="col-sm-2 control-label" for="id_image">Image</label>
    <div class="col-sm-10">
        <div class="row bootstrap3-multi-input">
            <div class="col-xs-12">
                <input class="" id="id_image" name="image" title="" type="file" />
            </div>
        </div>
    </div>
</div>
```

**Comment by dyve** [comment] 2015-10-26 06:03
I think this was intentional:
https://github.com/dyve/django-bootstrap3/blob/476404fa0328f0b855490ded6df4993445bef735/HISTORY.rst#256-2014-01-23

I don't use those fields often myself, would welcome feedback.

**Comment by beruic** [comment] 2015-10-28 14:04
Let me illustrate with screenshots. This is without ´class="form-control"´:
![without](https://cloud.githubusercontent.com/assets/724716/10790534/26dcdae8-7d84-11e5-97a9-096205aaf1e2.png)
and this is with:
![with](https://cloud.githubusercontent.com/assets/724716/10790544/30014db6-7d84-11e5-8d42-3a0adfdb320e.png)

I took a look at the commits for the version you mention @dyve, but could not find anything to the matter.

**Comment by dyve** [comment] 2015-10-30 05:19
I agree it looks much better with the form-control class. I will check e-mails and issues why this was removed. A little more patience please.

**Comment by dyve** [comment] 2015-10-30 05:33
The issue is with a ClearbleFileInput, if you just apply form-control it will become ugly. Trying to see if I can fix that better than just skipping form-control.

**Comment by dyve** [comment] 2015-10-30 06:04
It look like NOT applying form-control is according to Bootstrap docs:
http://getbootstrap.com/css/#forms-example

**Comment by beruic** [comment] 2015-11-25 11:58
I've had no problems with ClearbleFileInput, but I will let it be your call. Sorry for the long response time.

**Comment by dyve** [comment] 2016-10-25 07:41
Just wanted to say there is no clear right or wrong on this one. I choose to follow Bootstrap docs and not apply form-control. If anyone has a pull request that makes everything look much better, certainly willing to look into it again. Closing for now. Thanks for your time!

**Closed by dyve** 2016-10-25 07:41 UTC
Labels: awaiting feedback
