### ISSUE TITLE
different default button_class in dev and prod envirements

### ISSUE THREAD

**Issue by ant0n-z** [dyve/django-bootstrap3#371] opened 2017-02-12 17:10 UTC
When I use:
`{% buttons submit='OK' reset="Cancel" %}{% endbuttons %}`
in my development envirement, I see blue OK button 
`<div class="form-group"><button class="btn btn-primary" type="submit">OK</button> <button class="btn" type="reset">Cancel</button></div>`
but in production, I see white OK button 
`<div class="form-group"><button class="btn btn-default" type="submit">OK</button> <button class="btn btn-default" type="reset">Cancel</button></div>`
Sorry, is it bug or my inadvertence?

**Comment by marc-gist** [comment] 2017-03-16 12:32
Are you running different versions? as the current version of this only outputs with btn-default

I hope they will add a way to change this, either via settings, or an option inside the {% %} call.

**Comment by dyve** [comment] 2017-08-18 09:10
The only reason I can think of is if you are running different versions. Cannot reproduce it, so closing this.

**Closed by dyve** 2017-08-18 09:10 UTC
