### ISSUE TITLE
Settings don't seem to work. Django 1.7 & Python 3.4

### ISSUE THREAD

**Issue by AGTGreg** [dyve/django-bootstrap3#202] opened 2014-12-06 09:05 UTC
Hello,
I'm trying to configure django-bootstrap3 to display inline forms without any success. The configuration in settings.py seems to have no effect in how django-bootstrap3 spits out the forms.

I'm using django-bootstrap3 5.02 in django 1.7 and python 3.4.

Here's what I have:

In my settings.py:
```python
BOOTSTRAP3 = {
    'include_jquery': False,
    # Label class to use in horizontal forms
    'horizontal_label_class': 'col-md-2',
    # Field class to use in horizontal forms
    'horizontal_field_class': 'col-md-4',
    # Class to indicate required (better to set this in your Django form)
    'required_css_class': 'required',
}
```

In my form template:
```python
{% load bootstrap3 %}

{% bootstrap_form form layout='inline' %}
```

And here's the markup django-bootstrap3 generates:
```html
<input autofocus="autofocus" class="form-control" id="id_login" name="login" placeholder="E-mail address" required="required" title="" type="email">
```

Thank you in advance!

**Comment by keelung** [comment] 2015-01-14 00:32
Demo not works, I'm using Django 1.7.3 & Python 3.4.1 on Windows 7 SP1 32bits

D:\dev\GitHub\django-bootstrap3\demo>py manage.py runserver
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\dev\Python\lib\site-packages\django\core\management\__init__.py", line 387, in execute_from_command_line
    utility.execute()
  File "D:\dev\Python\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    django.setup()
  File "D:\dev\Python\lib\site-packages\django\__init__.py", line 18, in setup
    from django.utils.log import configure_logging
  File "D:\dev\Python\lib\site-packages\django\utils\log.py", line 13, in <module>
    from django.views.debug import ExceptionReporter, get_exception_reporter_filter
  File "D:\dev\Python\lib\site-packages\django\views\debug.py", line 10, in <module>
    from django.http import (HttpResponse, HttpResponseServerError,
  File "D:\dev\Python\lib\site-packages\django\http\__init__.py", line 2, in <module>
    from django.http.request import (HttpRequest, QueryDict,
  File "D:\dev\Python\lib\site-packages\django\http\request.py", line 15, in <module>
    from django.http.multipartparser import MultiPartParser, MultiPartParserError
  File "D:\dev\Python\lib\site-packages\django\http\multipartparser.py", line 11, in <module>
    import cgi
  File "D:\dev\Python\lib\cgi.py", line 42, in <module>
    import html
  File "D:\dev\GitHub\django-bootstrap3\bootstrap3\html.py", line 4, in <module>
    from django.forms.widgets import flatatt
  File "D:\dev\Python\lib\site-packages\django\forms\__init__.py", line 6, in <module>
    from django.forms.fields import *  # NOQA
  File "D:\dev\Python\lib\site-packages\django\forms\fields.py", line 18, in <module>
    from django.forms.utils import from_current_timezone, to_current_timezone
  File "D:\dev\Python\lib\site-packages\django\forms\utils.py", line 15, in <module>
    from django.utils.html import format_html, format_html_join, escape
  File "D:\dev\Python\lib\site-packages\django\utils\html.py", line 14, in <module>
    from django.utils.text import normalize_newlines
  File "D:\dev\Python\lib\site-packages\django\utils\text.py", line 13, in <module>
    from django.utils.six.moves import html_entities
  File "D:\dev\Python\lib\site-packages\django\utils\six.py", line 90, in __get__
    result = self._resolve()
  File "D:\dev\Python\lib\site-packages\django\utils\six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "D:\dev\Python\lib\site-packages\django\utils\six.py", line 80, in _import_module    __import__(name)
ImportError: No module named 'html.entities'; 'html' is not a package

**Comment by dyve** [comment] 2015-01-21 13:42
This is a known problem with Python 3.

**Comment by dyve** [comment] 2015-01-22 08:06
Duplicate of #140

**Closed by dyve** 2015-01-22 08:06 UTC

**Comment by royki** [comment] 2015-08-12 12:14
Is the problem fixed ?
